(()=>{const subs=['Prealgebra','Algebra','Geometry','Number Theory','Counting & Probability','Intermediate Algebra','Precalculus'];let s=NOW.load(),tries=0,p=null;const $=x=>document.querySelector(x),ri=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;const gcd=(a,b)=>b?gcd(b,a%b):a;const families={
'Prealgebra':[()=>{let a=ri(3,20),b=ri(3,15);return [`What is ${a} × ${b}?`,a*b,`Multiply ${a} by ${b}.`]},()=>{let a=ri(20,90),b=ri(2,9);return [`What is the remainder when ${a} is divided by ${b}?`,a%b,`${a} = ${Math.floor(a/b)}·${b} + ${a%b}.`]}],
'Algebra':[()=>{let x=ri(-8,12),a=ri(2,9),b=ri(-12,12);return [`Solve: ${a}x ${b>=0?'+ '+b:'− '+(-b)} = ${a*x+b}`,x,`Undo the constant, then divide by ${a}.`]},()=>{let r=ri(2,8),q=ri(2,8);return [`If x + 1/x = ${r}, what is x² + 1/x²?`,r*r-2,`Square the given expression and subtract 2.`]}],
'Geometry':[()=>{let a=ri(3,15),b=ri(3,15);return [`A rectangle has sides ${a} and ${b}. Find its area.`,a*b,`Area = length × width.`]},()=>{let k=ri(1,5),a=3*k,b=4*k;return [`A right triangle has legs ${a} and ${b}. Find its hypotenuse.`,5*k,`This is a scaled 3-4-5 triangle.`]}],
'Number Theory':[()=>{let a=ri(12,90),b=ri(12,90);return [`Find gcd(${a}, ${b}).`,gcd(a,b),`Use the Euclidean algorithm.`]},()=>{let b=ri(3,11),e=ri(4,20),m=ri(3,13);return [`What is the remainder when ${b}^${e} is divided by ${m}?`,(BigInt(b)**BigInt(e)%BigInt(m)).toString(),`Look for a cycle modulo ${m}.`]}],
'Counting & Probability':[()=>{let n=ri(5,10);return [`How many ways can 2 students be chosen from ${n} students?`,n*(n-1)/2,`Use C(${n},2).`]},()=>{let n=ri(2,6);return [`How many outcomes are possible when ${n} fair coins are flipped?`,2**n,`Each coin doubles the number of outcomes.`]}],
'Intermediate Algebra':[()=>{let r=ri(1,9),q=ri(1,9);return [`The roots of x² − ${r+q}x + ${r*q} are r and s. Find r²+s².`,r*r+q*q,`Use (r+s)²−2rs.`]},()=>{let a=ri(2,8),b=ri(2,8);return [`Expand (x + ${a})(x + ${b}). What is the coefficient of x?`,a+b,`The x coefficient is the sum of the constants.`]}],
'Precalculus':[()=>{let n=[0,30,45,60,90][ri(0,4)],ans={0:0,30:.5,45:'sqrt(2)/2',60:'sqrt(3)/2',90:1}[n];return [`What is sin(${n}°)?`,ans,`Use the special-angle unit circle values.`]},()=>{let a=ri(2,6),b=ri(2,6);return [`For z = ${a} + ${b}i, what is |z|²?`,a*a+b*b,`|a+bi|²=a²+b².`]}]};
function pick(){let arr=families[s.hmm.subject]||families.Prealgebra;p=arr[ri(0,arr.length-1)]();tries=0;$('#problem').textContent=p[0];$('#answer').value='';$('#feedback').innerHTML='';$('#tries').textContent='3 attempts';}
function renderSubs(){ $('#subjects').innerHTML=subs.map(x=>`<button class="${x===s.hmm.subject?'on':''}">${x}</button>`).join('');[...$('#subjects').children].forEach((b,i)=>b.onclick=()=>{s.hmm.subject=subs[i];NOW.save(s);renderSubs();pick()})}
function check(){let v=$('#answer').value.trim().toLowerCase().replace(/√/g,'sqrt');if(!v)return;tries++;s.hmm.attempts++;let ok=v===String(p[1]).toLowerCase();if(ok){s.hmm.correct++;s.hmm.streak++;let gain=Math.max(2,12-(tries-1)*4);s.hmm.rating+=gain;s.coins+=Math.max(1,4-(tries-1));NOW.save(s);$('#feedback').innerHTML=`<div class="good">CORRECT. +${gain} rating · +${Math.max(1,4-(tries-1))} 🪙</div><p>${p[2]}</p><button class="btn" id="next">NEXT →</button>`;$('#next').onclick=pick}else{ s.hmm.streak=0;s.hmm.rating=Math.max(0,s.hmm.rating-3);NOW.save(s);if(tries>=3){$('#feedback').innerHTML=`<div class="bad">THREE ATTEMPTS.</div><p>${p[2]} Answer: <b>${p[1]}</b></p><button class="btn" id="next">NEXT →</button>`;$('#next').onclick=pick}else $('#feedback').innerHTML=`<div class="bad">NOT YET.</div><p>${3-tries} attempt${3-tries===1?'':'s'} left.</p>`}$('#rating').textContent=s.hmm.rating;$('#coins').textContent=s.coins+' 🪙';$('#tries').textContent=Math.max(0,3-tries)+' attempts left'}
$('#check').onclick=check;$('#answer').onkeydown=e=>{if(e.key==='Enter')check()};$('#hint').onclick=()=>$('#feedback').innerHTML=`<p>HMM says: ${p[2]}</p>`;renderSubs();$('#rating').textContent=s.hmm.rating;$('#coins').textContent=s.coins+' 🪙';pick();})();